// 54 cartas de la Lotería
const CARDS = [
  { id:  1, name: 'Gallo',      emoji: '🐓' },
  { id:  2, name: 'Diablo',     emoji: '😈' },
  { id:  3, name: 'Princesa',   emoji: '👩' },
  { id:  4, name: 'Sombrero',   emoji: '🎩' },
  { id:  5, name: 'Sombrilla',  emoji: '☂️' },
  { id:  6, name: 'Sirena',     emoji: '🧜‍♀️' },
  { id:  7, name: 'Escalera',   emoji: '🪜' },
  { id:  8, name: 'Botella',    emoji: '🍾' },
  { id:  9, name: 'Barril',     emoji: '🛢️' },
  { id: 10, name: 'Árbol',      emoji: '🌳' },
  { id: 11, name: 'Melón',      emoji: '🍈' },
  { id: 12, name: 'Cuchillo',   emoji: '🗡️' },
  { id: 13, name: 'Militar',    emoji: '🪖' },
  { id: 14, name: 'Calavera',   emoji: '💀' },
  { id: 15, name: 'Pera',       emoji: '🍐' },
  { id: 16, name: 'Bandera',    emoji: '🚩' },
  { id: 17, name: 'Guitarra',   emoji: '🎸' },
  { id: 18, name: 'Violín',     emoji: '🎻' },
  { id: 19, name: 'Cisne',      emoji: '🦢' },
  { id: 20, name: 'Pájaro',     emoji: '🐦' },
  { id: 21, name: 'Mano',       emoji: '✋' },
  { id: 22, name: 'Bota',       emoji: '👢' },
  { id: 23, name: 'Luna',       emoji: '🌙' },
  { id: 24, name: 'Canario',    emoji: '🦜' },
  { id: 25, name: 'Cerveza',    emoji: '🍺' },
  { id: 26, name: 'Máscaras',   emoji: '🎭' },
  { id: 27, name: 'Corazón',    emoji: '❤️' },
  { id: 28, name: 'Sandía',     emoji: '🍉' },
  { id: 29, name: 'Tambor',     emoji: '🥁' },
  { id: 30, name: 'Camarón',    emoji: '🦐' },
  { id: 31, name: 'Arco',       emoji: '🏹' },
  { id: 32, name: 'Música',     emoji: '🎵' },
  { id: 33, name: 'Araña',      emoji: '🕷️' },
  { id: 34, name: 'Soldado',    emoji: '💂' },
  { id: 35, name: 'Estrella',   emoji: '⭐' },
  { id: 36, name: 'Sartén',     emoji: '🍳' },
  { id: 37, name: 'Planeta',    emoji: '🌍' },
  { id: 38, name: 'Pluma',      emoji: '🪶' },
  { id: 39, name: 'Cactus',     emoji: '🌵' },
  { id: 40, name: 'Escorpión',  emoji: '🦂' },
  { id: 41, name: 'Rosa',       emoji: '🌹' },
  { id: 42, name: 'Muerte',     emoji: '☠️' },
  { id: 43, name: 'Campana',    emoji: '🔔' },
  { id: 44, name: 'Jarrón',     emoji: '🏺' },
  { id: 45, name: 'Venado',     emoji: '🦌' },
  { id: 46, name: 'Sol',        emoji: '☀️' },
  { id: 47, name: 'Corona',     emoji: '👑' },
  { id: 48, name: 'Canoa',      emoji: '🚣' },
  { id: 49, name: 'Pino',       emoji: '🌲' },
  { id: 50, name: 'Pescado',    emoji: '🐟' },
  { id: 51, name: 'Palma',      emoji: '🌴' },
  { id: 52, name: 'Maceta',     emoji: '🪴' },
  { id: 53, name: 'Acordeón',   emoji: '🪗' },
  { id: 54, name: 'Rana',       emoji: '🐸' }
];

const CARD_MAP = new Map(CARDS.map(c => [c.id, c]));

module.exports = { CARDS, CARD_MAP };
